name: flutter_webrtc_demo
description: A new Flutter application.
version: 1.0.1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  google_fonts:
  flutter_webrtc: ^0.5.8
  shared_preferences: ^2.0.0
  http:
  path_provider:
  # intl: ^0.16.1
  intl: 0.17.0
  flutter_image_compress: ^0.6.8
  image_picker: ^0.6.3+1
  camera: ^0.5.8+7
  path:
  image_cropper: ^1.4.1
  # firebase_auth: ^0.14.0+5
  firebase_auth: 3.2.0
  # firebase_database: ^3.0.7
  firebase_database:
  # firebase_core: ^0.4.0
  firebase_core: ^1.6.0
  cloud_firestore:
  firebase_storage:
  json_annotation: ^3.1.1
  image: ^3.0.5
  firebase_auth_web: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/logoist.jpg
    - images/no_photo_selected.png